src/Tree.jsx
Selectable was read from Tree props before, so we can't let a part of TreeNodes not selectable. Changed to: prefer to use TreeNode's own selectable prop while renderTreeNode.
=> prefer to use TreeNode's own selectable prop

src/Tree.jsx, src/util.js
When the tree is displayed in a modal or similar, the current getOffset function does not calculate the correct offset for the onDragEnterGap function of the tree. This fixes the calculation and enables the tree on modals etc., too.
=> Fixed calculation of offset for onDragEnterGap

src/util.js, tests/Tree.spec.js
Close: https://github.com/ant-design/ant-design/issues/7277
=> fix: should calculate parent's checked status correctly, close: ant-design/ant-design#7277

src/Tree.jsx, tests/__snapshots__/Tree.spec.js.snap
`Received 'true' for non-boolean attribute 'unselectable'. If this is expected, cast the value to a string.`
=> Fix warning with latest react

examples/basic.js, src/TreeNode.jsx, tests/Tree.spec.js
Basically adapt advice of this [comment](https://github.com/react-component/tree/pull/128#issuecomment-331039655)
When Tree is checkable but not selectable, we dispatch check event when clicking on tree node.
=> make node clickable when not selectable

src/Tree.jsx, src/TreeNode.jsx
如果定义了 `onRightClick`，才阻止默认右键菜单出现。
=> Should not prevent right click

README.md, src/Tree.jsx, src/TreeNode.jsx, tests/Tree.spec.js, tests/TreeProps.spec.js
For [dir tree requirement](https://github.com/ant-design/ant-design/issues/7749), interactive operation need additional key press(e.g. ctrl, shift) which need native event info.
=> Pass nativeEvent to the event handler

src/Tree.jsx, src/TreeNode.jsx, tests/TreeProps.spec.js
To support user customize click/ dbl click selector expand.
Not prevent event trigger when TreeNode is disabled.
ref: https://github.com/ant-design/ant-design/pull/10139
=> Add onClick & onDoubleClick event handler

src/Tree.jsx, src/TreeNode.jsx, src/util.js, tests/TreeProps.spec.js, tests/__snapshots__/TreeProps.spec.js.snap, tests/util.spec.js
Same premise as https://github.com/react-component/tree/pull/172, except this one is for Tree.jsx.
This PR passes `data-` and `aria-` props to the root `<ul>`.
=> Render data- and aria- attributes

examples/basic.js, src/Tree.jsx, src/TreeNode.jsx, tests/Tree.spec.js
Internal store ref to enable `rc-tree-select` to find the selected DOM node.
ref: https://github.com/ant-design/ant-design/issues/14897
=> Internal store treeNodes ref

src/TreeNode.tsx
When I try to use the TypeScript types, it wants me to provide an `active` prop for `TreeNode`. Based on the documentation and the fact that the prop is under the "By parent" section, the user should not have to supply the `active` prop.
=> Make `active` TreeNode prop optional

src/Tree.tsx
When dragging from another tree, `this.dragNode` is null  and `convertNodePropsToEventData(this.dragNode)` will fail.
=> Handle this.dragNode === null

src/interface.tsx
`ScrollTo` 定义改从 `rc-virtual-list` 中获取
=> fix(typings): correct the definition of ScrollTo

src/Tree.tsx, src/util.tsx, tests/Tree.spec.js
fix https://github.com/ant-design/ant-design/issues/29470
coverage falls due to the line compression by prettier.
=> fix: only allow cross level horziontal drop when physical drop node is the last child itself

README.md, src/Tree.tsx, src/util.tsx, tests/Tree.spec.js
Pass `dragNode` info when check `allowDrop` which can help us to decide which case should be allow trigger drop event
=> feat: add dragnode info into tree#allowdrop

src/Tree.tsx
Resolves ant-design/ant-design#31555, resolves #477
=> fix: hide indicator outside the droppable area (#477)

src/Tree.tsx
https://github.com/react-component/tree/pull/503 introduced generic types but the `onCheck` type was not set correctly
=> fix(tree-type): fix generic type for onCheck

package.json, src/TreeNode.tsx, tests/React18.spec.tsx, tests/util.spec.js
现在 React 正式版是 18.2，测试实际上写了是测不出来，需要手工临时安装一下 React 18 next 版本才行。另外移除 WrapperNode 的 `defaultProps` 后会导致节点遍历时也就不会有这个值了，考虑到用户其实不会遍历 Tree children 并且还不设置 title，测试变化符合预期。
fix https://github.com/ant-design/ant-design/issues/41325
=> chore: fix React 18.3 warning

src/NodeList.tsx
fix [Tree 组件删除其中一个节点的时候页面会闪一下 ant-design/ant-design#41878](https://github.com/ant-design/ant-design/issues/41878)
> 我对react的了解并不是很深入，就这个问题的思考，如有问题可以及时和我沟通
* 我尝试去定位问题所在，发现页面闪烁是由于treeData发生变换之后 Inden 组件所接受的 level 发生了变化所导致的。
* 随后去定位 level 的变化发现 level 的值是通过 keyEntity 所获取的
* 我个人认为闪烁的原因是因为treeData发生更新后  tree 组件重新构造出新的 state，同时 state 下的 keyEntity 同样发生变化，由于 TreeNode 组件引入 keyEntity 是通过 Context 引入，因此在第一次更新阶段 level 发生变化，造成了 Inden 组件获取到更新后的 level造成了闪烁。而后续的第二次更新是由 NodeList 组件中的 useEffect 所产生，在第二次更新中对渲染 Tree 组件的 data 进行更新，随后删除了对应的节点
* 而 useLayoutEffct 好像本身便是处理该问题的 hook
> 在rc-tree库下，我通过了所有的测试用例。但在antd下的测试用例我无法进行准确的判断
closes #741 #742
=> fix: TreeNode false flicker in re-render

docs/examples/animation.jsx, src/MotionTreeNode.tsx, src/useUnmount.ts, tests/TreeMotion.spec.tsx
ref https://github.com/ant-design/ant-design/issues/43038
根本原因是 motion 默认为 `true`，通过 effect 切换为 `false` 会触发多个切换事件，只需要过滤无用事件即可。#735 用了 timeout，导致按帧计算时无动画时会被永久跳过。
=> fix: disabled motion will never end

src/MotionTreeNode.tsx, src/useUnmount.ts, tests/TreeMotion.spec.tsx
fix https://github.com/ant-design/ant-design/issues/43282
When in motion, dynamic modify `treeData` will block to make Tree always in motion status.
=> fix: merge onMotionLogic into one set

src/TreeNode.tsx
fix https://github.com/ant-design/ant-design/issues/43493
这个在 React 生命周期的 act 内会合并掉，外侧是测不到的。只有打断点才能停到，场景过于特殊写不了测试。
=> fix: No blink for tree node

src/Tree.tsx
When implementing the onCheck handler, there are no accessible type definitions for the parameters at present.
=> fix: Access CheckInfo interface for types when declaring onCheck handler

src/NodeList.tsx, src/Tree.tsx, src/TreeNode.tsx, src/contextTypes.ts, src/interface.tsx, src/util.tsx, src/utils/conductUtil.ts, src/utils/keyUtil.ts, src/utils/treeUtil.ts
对外接口对齐 React.Key，内部抽出 KeyEntities 定义和转化方法。等 TS 支持 bigint 类型，可以做统一处理。
ref https://github.com/DefinitelyTyped/DefinitelyTyped/pull/66723
=> chore: follow up types update

tests/Tree.spec.tsx
The implementation of rc-virtual-list has changed and is more async.  Fixed the associated test by adding act.  This is what they've done in the rc-virtual-list tests too:
https://github.com/react-component/virtual-list/blob/baf75273ba1f6106b87c635b9b951466537646d7/tests/scroll.test.js#L101
=> Fix async issue with scrollTo test

.npmrc
Webpack 4 requires this workaround in order to work with node 17+.  This should fix the Vercel deploys.
=> Webpack 4 and Node 17 incompatibility fix

src/Tree.tsx
Improve type information for onClick and onDoubleClick handlers.  Pass through generics.
Before:
After:
=> Improve type information for onClick and onDoubleClick handlers

docs/examples/draggable.jsx, src/Tree.tsx, src/util.tsx, tests/TreeDraggable.spec.tsx, tests/TreeProps.spec.tsx, tests/__snapshots__/TreeProps.spec.tsx.snap
resolve https://github.com/ant-design/ant-design/issues/47180
测试用例有几个 magic number 看了一下，应该也是因为这个递归计算问题导致的。
=> fix: Drag over expanded empty node should work as normal node
