react-component/tree

- package.json
- src/TreeNode.jsx
> Fix react-unknown-prop warnings

- src/Tree.jsx
- tests/Tree.spec.js
fix: https://github.com/ant-design/ant-design/issues/4553, #50
> Fix checkStrictly not working under uncontrolled mode

- src/Tree.jsx
- tests/Tree.spec.js
Close: https://github.com/react-component/tree/issues/85
> feat: shoud not trigger onDragEnter immediately, close: #85

- src/Tree.jsx
- src/util.js
- tests/Tree.spec.js
close https://github.com/ant-design/ant-design/issues/6891
close https://github.com/react-component/tree/issues/99
> Ignore disabledCheck item

- src/Tree.jsx
- src/util.js
- tests/Tree.spec.js
> Fix disable item check state

- src/Tree.jsx
- src/util.js
> remove interactive logic

- src/Tree.jsx
- src/TreeNode.jsx
- src/util.js
> support conditional rendering

- examples/contextmenu.js
- src/Tree.jsx
- tests/Tree.spec.js
> Fix rightClick change selected item

- examples/util.js
- src/Tree.jsx
- src/util.js
Eliminate String.split() and compare position strings directly.
Gives huge performance boost when handling lots of nodes, e.g.
https://react-component.github.io/tree-select/examples/big-data.html
> Optimize node ancestor checks

- tests/TreeNodeProps.spec.js
- tests/TreeProps.spec.js
- tests/__snapshots__/TreeNodeProps.spec.js.snap
- tests/__snapshots__/TreeProps.spec.js.snap
Code refactor prepare. Add more props check in test case.
> [WIP] add test case for basic props

- examples/dynamic.js
- src/TreeNode.jsx
- tests/TreeProps.spec.js
- tests/__snapshots__/TreeProps.spec.js.snap
ref: https://github.com/ant-design/ant-design/issues/9920
> fix loadData for state not sync

- examples/draggable.js
- src/Tree.jsx
- src/TreeNode.jsx
- src/util.js
Drag position will auto refresh when dragging. To avoid fixed drag position on `dragEnter` fire.
ref: https://github.com/react-component/tree/issues/132
> adjust drag logic to make drag more smooth

- examples/icon.js
- src/Tree.jsx
- src/TreeNode.jsx
- tests/TreeProps.spec.js
- tests/__snapshots__/TreeProps.spec.js.snap
Add icon prop on Tree component
ref: https://github.com/ant-design/ant-design/issues/7749#issuecomment-378496607
To support `<DirectoryTree>`
> Add icon prop on Tree component

- README.md
- package.json
- src/Tree.jsx
- src/TreeNode.jsx
- tests/TreeProps.spec.js
* Add `loadedKeys`
* Add `onLoad`
* Add test case
* Update doc
> Make tree node load as control prop

- src/TreeNode.jsx
- tests/TreeNodeProps.spec.js
- tests/__snapshots__/TreeNodeProps.spec.js.snap
Pass TreeNode data-* and aria-* props to the li for testing or accessiblity
> Pass TreeNode data-* and aria-* props to the li

- src/TreeNode.jsx
If not, dragging prevents normal working of custom drag logic, applied to tree leafs.
> dont apply drag methods if not draggable

- assets/index.less
- examples/basic-controlled.js
- examples/basic.js
- examples/big-data-generator.js
- examples/big-data.js
- examples/contextmenu.js
- examples/draggable.js
- examples/dropdown.js
- examples/icon.js
- examples/util.js
- package.json
- src/Tree.jsx
- src/TreeNode.jsx
- src/index.js
- src/util.js
- tests/Tree.spec.js
- tests/__snapshots__/Tree.spec.js.snap
- tests/__snapshots__/TreeNodeProps.spec.js.snap
- tests/__snapshots__/TreeProps.spec.js.snap
> Deps update

- .nowignore
- examples/animation.js
- now.json
- package.json
- src/Tree.jsx
- src/TreeNode.jsx
- tests/TreeProps.spec.js
Draft. Please help to review this.
> feat: use CSSMotion to make animation pure with React

- README.md
- examples/basic.js
- src/TreeNode.jsx
- tests/TreeProps.spec.js
ref: https://github.com/ant-design/ant-design/issues/16316
> feat: TreeNode support `checkable`

- src/Tree.jsx
> fix: onDragEnter this.dragNode undefined

- package.json
- src/Tree.tsx
- src/TreeNode.tsx
- src/contextTypes.ts
- tests/Tree.spec.js
- tests/TreeProps.spec.js
- tests/util.js
- tests/util.spec.js
> refactor: Use new React context api

- examples/animation-draggable.jsx
- package.json
- src/NodeList.tsx
- src/Tree.tsx
- tests/TreeNodeProps.spec.js
- tests/__snapshots__/Tree.spec.js.snap
- tests/__snapshots__/TreeProps.spec.js.snap
https://rc-tree-6tyz9zlsv.now.sh/iframe.html?selectedKind=rc-tree&selectedStory=animation-draggable
> feat: Support drag with animation

- .eslintrc.js
- assets/index.less
- examples/animation.jsx
- examples/animation.less
- examples/basic.jsx
- examples/funtionTitle.jsx
- package.json
- src/MotionTreeNode.tsx
- src/NodeList.tsx
- src/Tree.tsx
- src/TreeNode.tsx
- src/contextTypes.ts
- src/interface.tsx
- src/util.tsx
- src/utils/treeUtil.ts
- tests/Accessibility.spec.js
- tests/Tree.spec.js
- tests/TreeProps.spec.js
- tests/__snapshots__/Tree.spec.js.snap
- tests/__snapshots__/TreeNodeProps.spec.js.snap
- tests/__snapshots__/TreeProps.spec.js.snap
> feat: Accessibility & keyboard support

- .eslintrc.js
- .prettierrc
- src/Tree.tsx
- tests/Tree.spec.js
fix https://github.com/ant-design/ant-design/issues/19893
> fix: Not crash when expandedKeys change to undefined

- package.json
- src/Tree.tsx
- tests/Tree.spec.js
fix https://github.com/ant-design/ant-design/issues/20768
> fix: Tree State should keep sync instead of part update

- .eslintrc.js
- .prettierrc
- src/utils/conductUtil.ts
- tests/util.spec.js
fix https://github.com/ant-design/ant-design/issues/22356
> fix: Tree conduct logic

- examples/basic.jsx
- src/Tree.tsx
- tests/Accessibility.spec.js
fix https://github.com/ant-design/ant-design/issues/22839
fix https://github.com/react-component/tree/issues/305
> fix: Active trigger logic

- src/interface.tsx
ref https://github.com/ant-design/ant-design/issues/22138
> Tree Component Async loadData Type problem

- src/Tree.tsx
- tests/Tree.spec.js
ref: https://github.com/ant-design/ant-design/issues/23616
> fix: Drag should not works on nest children

- package.json
- src/NodeList.tsx
- src/Tree.tsx
- tests/TreeMotion.spec.js
- tests/TreeProps.spec.js
fix https://github.com/ant-design/ant-design/issues/23848
> chore: Lock expand when in motion

- package.json
ref: https://github.com/react-component/tree/pull/341#issuecomment-643275527
> fix: pre-commit hook

- src/TreeNode.tsx
- tests/__snapshots__/Tree.spec.js.snap
- tests/__snapshots__/TreeNodeProps.spec.js.snap
- tests/__snapshots__/TreeProps.spec.js.snap
ref pr: https://github.com/ant-design/ant-design/pull/25067
ref comment: https://github.com/ant-design/ant-design/pull/25067#issuecomment-647429051
> feat: add last className for Treeleaf

- src/Tree.tsx
- src/TreeNode.tsx
- src/contextTypes.ts
- tests/TreeProps.spec.js
ref https://github.com/ant-design/ant-design/issues/25615
> feat: Support titleRender

- README.md
- examples/treeNodeLabelProp.tsx
- src/NodeList.tsx
- src/Tree.tsx
- tests/TreeProps.spec.js
直接落到 `rc-tree` 里省的多走一层：
ref https://github.com/ant-design/ant-design/issues/23079
> support treeNodeLabelProp

- src/NodeList.tsx
ref https://github.com/ant-design/ant-design/issues/25682
> fix: Not calculate for scroll when virtual is false

- src/Tree.tsx
- src/TreeNode.tsx
- src/contextTypes.ts
> feat: types enhancing(#356)

- src/contextTypes.ts
Fix my mistake in one type. Sorry for that. I'm a newbie in contributing  some projects
> fix: wrong type(#356)

- package.json
- src/Indent.tsx
- tests/__snapshots__/Tree.spec.js.snap
- tests/__snapshots__/TreeNodeProps.spec.js.snap
- tests/__snapshots__/TreeProps.spec.js.snap
> feat: add Indent end-first-level class

- src/MotionTreeNode.tsx
- src/NodeList.tsx
- tests/TreeMotion.spec.js
fix https://github.com/ant-design/ant-design/issues/26429
> fix: Motion check logic

- package.json
- src/Tree.tsx
- tests/TreeProps.spec.js
close https://github.com/ant-design/ant-design/issues/26380
> fix: Tree should support onContextMenu

- .eslintrc.js
- .travis.yml
- assets/index.less
- examples/animation.jsx
- examples/animation.less
- examples/big-data.jsx
- examples/dropdown.jsx
- package.json
- src/Indent.tsx
- src/util.tsx
- tests/__snapshots__/Tree.spec.js.snap
- tests/__snapshots__/TreeNodeProps.spec.js.snap
- tests/__snapshots__/TreeProps.spec.js.snap
- tests/util.spec.js
ref ant-design/ant-design#27364
> fix: Fix Indent to correct level 

- src/TreeNode.tsx
- tests/Tree.spec.js
fix issue [#28349](https://github.com/ant-design/ant-design/issues/28349)
> 修复动态加载数据时重复点击展开节点会导致状态错误的问题

- src/NodeList.tsx
- src/Tree.tsx
- tests/__snapshots__/Tree.spec.js.snap
- tests/__snapshots__/TreeNodeProps.spec.js.snap
- tests/__snapshots__/TreeProps.spec.js.snap
update `role="tree"` to outside.
Close: ant-design/ant-design#30008
> fix: update role pos

- src/Tree.tsx
- src/TreeNode.tsx
- tests/Tree.spec.js
- tests/TreeProps.spec.js
https://github.com/ant-design/ant-design/issues/31141
> fix: Tree state when loadData fail

- src/NodeList.tsx
- src/Tree.tsx
- tests/__snapshots__/Tree.spec.js.snap
- tests/__snapshots__/TreeNodeProps.spec.js.snap
- tests/__snapshots__/TreeProps.spec.js.snap
Reverts react-component/tree#460
It should be a keyboard support feature.
> Revert "fix: update role pos"

- src/NodeList.tsx
- src/Tree.tsx
- tests/__snapshots__/Tree.spec.js.snap
- tests/__snapshots__/TreeNodeProps.spec.js.snap
- tests/__snapshots__/TreeProps.spec.js.snap
close ant-design/ant-design#30008
close https://github.com/ant-design/ant-design/issues/31215
close https://github.com/ant-design/ant-design/issues/31216
Original PR: https://github.com/react-component/tree/pull/460
> fix: Tree role attribute

- package.json
> chore(deps): bump rc-virtual-list from 3.0.1 to 3.2.0

- src/Tree.tsx
- tests/Tree.spec.js
close https://github.com/ant-design/ant-design/issues/31413
> fix: onScroll should pass to VirtualList

- src/Tree.tsx
- src/contextTypes.ts
This PR updates type for `NodeDragEventParams` and `NodeDragEventHandler`
> Update Type for NodeDragEventParams

- package.json
- src/NodeList.tsx
- tests/TreeMotion.spec.js
resolve https://github.com/ant-design/ant-design/issues/31975
> fix: Not do motion when TreeNode is out of scope

- src/Tree.tsx
resolve https://github.com/ant-design/ant-design/issues/32037
比较蛋疼，测试里怎么写都是同步的。看来是被 enzyme 强制 update 了。
> fix: loadingKey use provided

- docs/examples/draggable.jsx
- src/Tree.tsx
- src/TreeNode.tsx
- src/contextTypes.ts
- tests/TreeDraggable.spec.js
https://github.com/ant-design/ant-design/pull/32306#discussion_r716331631
> refactor: Merge draggable api

- src/Tree.tsx
- tests/TreeProps.spec.js
resolve https://github.com/ant-design/ant-design/issues/32313
> chore: Retry 10 times after failed

- src/NodeList.tsx
- src/Tree.tsx
- src/TreeNode.tsx
- src/contextTypes.ts
- src/index.ts
- src/interface.tsx
- src/util.tsx
- src/utils/conductUtil.ts
- src/utils/treeUtil.ts
- tests/type.spec.tsx
- tests/util.spec.js
ref: https://github.com/ant-design/ant-design/issues/32912
> feat: Tree support generic

- src/util.tsx
> fix: If set selectedKeys or expandedKeys to undefined, will be error

- docs/examples/draggable.jsx
- src/Tree.tsx
- tests/TreeDraggable.spec.js
resolve https://github.com/ant-design/ant-design/issues/33397
> fix: Elements outside tree shouldn't trigger drag event

- docs/examples/draggable.jsx
- src/util.tsx
- tests/TreeDraggable.spec.js
https://github.com/ant-design/ant-design/issues/33624
> fix: draggable not support field names

- src/Tree.tsx
- tests/Accessibility.spec.js
ref https://github.com/ant-design/ant-design/issues/33744
> feat: Support activeKey

- src/Tree.tsx
- src/util.tsx
use Typescript version >= 3.7
we can use Optional Chaining replace
```
if(function){
function();
}
```
> refactor(optional chaining): use Optional Chaining replace if(funtion ){function()}

- package.json
We recently made a fix in `rc-virtual-list` so it would be awesome if we can bring those changes in here as well.
Refer -  https://github.com/react-component/virtual-list/pull/167
> chore(dep-update): rc-virtual-list version upgrade

- README.md
- docs/demo/expandAction.md
- docs/examples/expandAction.jsx
- docs/examples/expandAction.less
- src/Tree.tsx
- tests/TreeProps.spec.js
See https://github.com/react-component/tree/pull/542#issuecomment-1105189331 for more details.
> Feat: add 'expandAction' prop for Tree.

- src/NodeList.tsx
- tests/TreeMotion.spec.js
resolve https://github.com/ant-design/ant-design/issues/35199
> fix: NodeList sync should not use closure ood data

- src/NodeList.tsx
- src/Tree.tsx
- src/contextTypes.ts
- src/interface.tsx
- src/util.tsx
- src/utils/treeUtil.ts
ref https://github.com/ant-design/ant-design/pull/35618
> chore: More proper ts def

- src/Tree.tsx
- tests/TreeDraggable.spec.tsx
fix https://github.com/ant-design/ant-design/issues/34701
> fix: clean up when treeNode stop drag

- package.json
- src/TreeNode.tsx
> type: add id prop

- src/NodeList.tsx
Solves react-component/tree#629
> 🐛 adds missing constraint for TreeDataType

- src/Tree.tsx
close https://github.com/react-component/tree/issues/663
> fix activeKey type (Key => Key | null)

- src/NodeList.tsx
- tests/__snapshots__/Tree.spec.tsx.snap
- tests/__snapshots__/TreeNodeProps.spec.tsx.snap
- tests/__snapshots__/TreeProps.spec.tsx.snap
https://github.com/ant-design/ant-design/pull/39204
> style: set hidden treeNode's height strict to 0

- src/TreeNode.tsx
ref https://github.com/react-component/tree/pull/732#discussion_r1141284769
> chore: clean up

- src/MotionTreeNode.tsx
- tests/TreeMotion.spec.tsx
修复StrictMode下，重跑effect导致动画失效。
fix https://github.com/ant-design/ant-design/issues/41120
> fix: invalid animation

- src/MotionTreeNode.tsx
- src/TreeNode.tsx
- src/index.ts
- src/interface.tsx
- src/util.tsx
- src/utils/treeUtil.ts
relate https://github.com/ant-design/ant-design/pull/42750
> refactor: solve circule dependency

- src/interface.tsx
Fixes #761 (transpilation error on project using rc-tree (directly or not) with option `skipLibCheck` set to `false`)
> Fixes transpilation error

- src/Tree.tsx
close https://github.com/ant-design/ant-design/issues/45265
> feat: add item scroll offset property

- src/Tree.tsx
- tests/Tree.spec.tsx
ref https://github.com/ant-design/ant-design/issues/44492 https://github.com/ant-design/ant-design/issues/45265
> fix: activeChange add offset

- src/useUnmount.ts
ref: https://github.com/ant-design/ant-design/discussions/45539
> fix: fix ssr warning

- package.json
> chore: fix npm package

- src/utils/treeUtil.ts
对convertDataToEntities函数的返回值增加类型注解
https://github.com/ant-design/ant-design/pull/47567#discussion_r1500628830
> add type annotate

- .husky/pre-commit
- .prettierignore
- .prettierrc
- package.json
- src/NodeList.tsx
- src/Tree.tsx
- src/contextTypes.ts
- src/interface.tsx
- src/util.tsx
- src/utils/conductUtil.ts
- src/utils/diffUtil.ts
- src/utils/keyUtil.ts
- src/utils/treeUtil.ts
Reverts react-component/tree#877
> Revert "type: React.Key => SafeKey"
